name: 'Run rails_best_practices with reviewdog'
description: '🐶 Run rails_best_practices with reviewdog on pull requests to improve code review experience.'
author: 'blooper05'
inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    default: '${{ github.token }}'
  workdir:
    description: 'Working directory relative to the root directory.'
    default: '.'
  ### Flags for reviewdog ###
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'error'
  reporter:
    description: 'Reporter of reviewdog command [github-check,github-pr-review].'
    default: 'github-check'
  filter_mode:
    description: |
      Filtering mode for the reviewdog command [added,diff_context,file,nofilter].
      Default is added.
    default: 'added'
  fail_on_error:
    description: |
      Exit code for reviewdog when errors are found [true,false]
      Default is `false`.
    default: 'false'
  reviewdog_flags:
    description: 'Additional reviewdog flags'
    default: ''
  ### Flags for rails_best_practices ###
  locale:
    description: '-locale flag of misspell. (US/UK)'
    default: ''
runs:
  using: 'composite'
  steps:
    - uses: reviewdog/action-setup@v1
      with:
        reviewdog_version: v0.14.1
    - run: $GITHUB_ACTION_PATH/script.sh
      shell: bash
      env:
        # INPUT_<VARIABLE_NAME> is not available in Composite run steps
        # https://github.community/t/input-variable-name-is-not-available-in-composite-run-steps/127611
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_LEVEL: ${{ inputs.level }}
        INPUT_REPORTER: ${{ inputs.reporter }}
        INPUT_FILTER_MODE: ${{ inputs.filter_mode }}
        INPUT_FAIL_ON_ERROR: ${{ inputs.fail_on_error }}
        INPUT_REVIEWDOG_FLAGS: ${{ inputs.reviewdog_flags }}
        INPUT_ESLINT_FLAGS: ${{ inputs.eslint_flags }}
        INPUT_WORKDIR: ${{ inputs.workdir }}
        INPUT_TOOL_NAME: ${{ inputs.tool_name }}

# Ref: https://haya14busa.github.io/github-action-brandings/
branding:
  icon: 'check-circle'
  color: 'red'
