---
name: Run rails_best_practices with reviewdog
description: 🐶 Run rails_best_practices with reviewdog on pull requests to improve code review experience.
author: blooper05
inputs:
  github_token:
    description: GITHUB_TOKEN
    default: ${{ github.token }}
  workdir:
    description: Working directory relative to the root directory.
    default: .
  ### Flags for reviewdog ###
  tool_name:
    description: Tool name to use for reviewdog reporter.
    default: rails_best_practices
  level:
    description: Report level for reviewdog [info,warning,error].
    default: error
  reporter:
    description: Reporter of reviewdog command [github-check,github-pr-review,github-pr-check,sarif].
    default: github-check
  filter_mode:
    description: |
      Filtering mode for the reviewdog command [added,diff_context,file,nofilter].
      Default is `added` except that sarif reporter uses `nofilter`.
    default: ''
  fail_on_error:
    description: |
      Exit code for reviewdog when errors are found [true,false].
      Default is `false`.
    default: 'false'
  reviewdog_flags:
    description: Additional reviewdog flags.
    default: ''
  output_dir:
    description: Output directory of reviewdog result. Useful for -reporter=sarif
    default: ../reviewdog-results
  ### Flags for rails_best_practices ###
  rails_best_practices_version:
    description: rails_best_practices version
  rails_best_practices_flags:
    description: |
      rails_best_practices flags (rails_best_practices --without-color --silent . <rails_best_practices_flags>)
    default: ''
runs:
  using: composite
  steps:
    - uses: reviewdog/action-setup@e04ffabe3898a0af8d0fb1af00c188831c4b5893  # v1.3.2
      with:
        reviewdog_version: v0.20.3
    - run: $GITHUB_ACTION_PATH/script.sh
      shell: bash
      env:
        # INPUT_<VARIABLE_NAME> is not available in Composite run steps
        # https://github.community/t/input-variable-name-is-not-available-in-composite-run-steps/127611
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_WORKDIR: ${{ inputs.workdir }}
        INPUT_TOOL_NAME: ${{ inputs.tool_name }}
        INPUT_LEVEL: ${{ inputs.level }}
        INPUT_REPORTER: ${{ inputs.reporter }}
        INPUT_FILTER_MODE: ${{ inputs.filter_mode }}
        INPUT_FAIL_ON_ERROR: ${{ inputs.fail_on_error }}
        INPUT_REVIEWDOG_FLAGS: ${{ inputs.reviewdog_flags }}
        INPUT_OUTPUT_DIR: ${{ inputs.output_dir }}
        INPUT_RAILS_BEST_PRACTICES_VERSION: ${{ inputs.rails_best_practices_version }}
        INPUT_RAILS_BEST_PRACTICES_FLAGS: ${{ inputs.rails_best_practices_flags }}
    - if: inputs.reporter == 'sarif'
      uses: github/codeql-action/upload-sarif@6bb031afdd8eb862ea3fc1848194185e076637e5  # v3.28.11
      with:
        sarif_file: ${{ inputs.output_dir }}

# Ref: https://haya14busa.github.io/github-action-brandings/
branding:
  icon: check-circle
  color: red
